// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: card.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Color 颜色
type Color int32

const (
	// 未设置
	Color_ColorUnset Color = 0
	// blue 23
	Color_ColorBlue Color = 1
	// gray 23
	Color_ColorGray Color = 2
	// brown 21
	Color_ColorBrown Color = 3
	// green 19
	Color_ColorGreen Color = 4
	// yellow 19
	Color_ColorYellow Color = 5
	// red 15
	Color_ColorRed Color = 6
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "ColorUnset",
		1: "ColorBlue",
		2: "ColorGray",
		3: "ColorBrown",
		4: "ColorGreen",
		5: "ColorYellow",
		6: "ColorRed",
	}
	Color_value = map[string]int32{
		"ColorUnset":  0,
		"ColorBlue":   1,
		"ColorGray":   2,
		"ColorBrown":  3,
		"ColorGreen":  4,
		"ColorYellow": 5,
		"ColorRed":    6,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

// POI 兴趣点
type POI int32

const (
	POI_POIUnset    POI = 0
	POI_POIMountain POI = 1
	POI_POIBuilding POI = 2
	POI_POITree     POI = 3
	POI_POIWater    POI = 4
	POI_POIField    POI = 5
)

// Enum value maps for POI.
var (
	POI_name = map[int32]string{
		0: "POIUnset",
		1: "POIMountain",
		2: "POIBuilding",
		3: "POITree",
		4: "POIWater",
		5: "POIField",
	}
	POI_value = map[string]int32{
		"POIUnset":    0,
		"POIMountain": 1,
		"POIBuilding": 2,
		"POITree":     3,
		"POIWater":    4,
		"POIField":    5,
	}
)

func (x POI) Enum() *POI {
	p := new(POI)
	*p = x
	return p
}

func (x POI) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (POI) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[1].Descriptor()
}

func (POI) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[1]
}

func (x POI) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use POI.Descriptor instead.
func (POI) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

// GameData 游戏数据
type GameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// animals 动物卡牌
	Animals []*Card `protobuf:"bytes,1,rep,name=animals,proto3" json:"animals,omitempty"`
}

func (x *GameData) Reset() {
	*x = GameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameData) ProtoMessage() {}

func (x *GameData) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameData.ProtoReflect.Descriptor instead.
func (*GameData) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *GameData) GetAnimals() []*Card {
	if x != nil {
		return x.Animals
	}
	return nil
}

// Card 卡牌描述
type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// kind 卡牌分类
	Kind POI `protobuf:"varint,2,opt,name=kind,proto3,enum=types.POI" json:"kind,omitempty"`
	// scores 得分
	Scores []int32 `protobuf:"varint,3,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	// pattern 需要条件
	Pattern []*Token `protobuf:"bytes,4,rep,name=pattern,proto3" json:"pattern,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetKind() POI {
	if x != nil {
		return x.Kind
	}
	return POI_POIUnset
}

func (x *Card) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *Card) GetPattern() []*Token {
	if x != nil {
		return x.Pattern
	}
	return nil
}

// Token 条件描述
type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// poi 兴趣点
	Poi POI `protobuf:"varint,1,opt,name=poi,proto3,enum=types.POI" json:"poi,omitempty"`
	// animal 放置动物，标记 (0, 0)
	Animal bool `protobuf:"varint,2,opt,name=animal,proto3" json:"animal,omitempty"`
	// delta_q 相对于动物格偏移 q
	DeltaQ int32 `protobuf:"varint,3,opt,name=delta_q,json=deltaQ,proto3" json:"delta_q,omitempty"`
	// delta_r 相对于动物格偏移 r
	DeltaR int32 `protobuf:"varint,4,opt,name=delta_r,json=deltaR,proto3" json:"delta_r,omitempty"`
	// height 需要高度
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetPoi() POI {
	if x != nil {
		return x.Poi
	}
	return POI_POIUnset
}

func (x *Token) GetAnimal() bool {
	if x != nil {
		return x.Animal
	}
	return false
}

func (x *Token) GetDeltaQ() int32 {
	if x != nil {
		return x.DeltaQ
	}
	return 0
}

func (x *Token) GetDeltaR() int32 {
	if x != nil {
		return x.DeltaR
	}
	return 0
}

func (x *Token) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_card_proto protoreflect.FileDescriptor

var file_card_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x25, 0x0a, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x07, 0x61,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x22, 0x7a, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x4f, 0x49, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x07, 0x70, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x03,
	0x70, 0x6f, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x50, 0x4f, 0x49, 0x52, 0x03, 0x70, 0x6f, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x5f, 0x71, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x51, 0x12, 0x17, 0x0a, 0x07, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x5f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x52, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2a, 0x74, 0x0a, 0x05,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x55, 0x6e,
	0x73, 0x65, 0x74, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x6c,
	0x75, 0x65, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x72, 0x61,
	0x79, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x72, 0x6f, 0x77,
	0x6e, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x72, 0x65, 0x65,
	0x6e, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x59, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x64,
	0x10, 0x06, 0x2a, 0x5e, 0x0a, 0x03, 0x50, 0x4f, 0x49, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x49,
	0x55, 0x6e, 0x73, 0x65, 0x74, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4f, 0x49, 0x4d, 0x6f,
	0x75, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4f, 0x49, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x49,
	0x54, 0x72, 0x65, 0x65, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x49, 0x57, 0x61, 0x74,
	0x65, 0x72, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x49, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x10, 0x05, 0x42, 0x73, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42,
	0x09, 0x43, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x7a, 0x79, 0x6a, 0x65, 0x72, 0x72,
	0x79, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x65, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x05, 0x54, 0x79,
	0x70, 0x65, 0x73, 0xca, 0x02, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0xe2, 0x02, 0x11, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData = file_card_proto_rawDesc
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_card_proto_rawDescData)
	})
	return file_card_proto_rawDescData
}

var file_card_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_card_proto_goTypes = []any{
	(Color)(0),       // 0: types.Color
	(POI)(0),         // 1: types.POI
	(*GameData)(nil), // 2: types.GameData
	(*Card)(nil),     // 3: types.Card
	(*Token)(nil),    // 4: types.Token
}
var file_card_proto_depIdxs = []int32{
	3, // 0: types.GameData.animals:type_name -> types.Card
	1, // 1: types.Card.kind:type_name -> types.POI
	4, // 2: types.Card.pattern:type_name -> types.Token
	1, // 3: types.Token.poi:type_name -> types.POI
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_card_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_card_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		EnumInfos:         file_card_proto_enumTypes,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_rawDesc = nil
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
